CREATE DATABASE `GAME OF THRONES`;

USE `GAME OF THRONES`;

set autocommit=0;

COMMIT;

CREATE TABLE `PERSONAGENS` (
  `NOME_DO_ATOR` varchar(200) PRIMARY KEY,
  `PERSONAGEM` varchar(200),
  `APARICOES` int,
  `PRIMEIRA_APARICAO` varchar(50),
  `ULTIMA_APARICAO` varchar(50)
);

CREATE TABLE `EPISODIOS` (
  `ID` int PRIMARY KEY,
  `NOME_DO_EP` varchar(200),
  `TEMPORADA` varchar(50),
  `LANCAMENTO` varchar(50),
  `TEMPO_DE_DURACAO` int,
  `DIRETOR` varchar(200),
  `RATINGS` float,
  `ESTRELA_1` varchar(200)
);

ALTER TABLE `EPISODIOS` ADD FOREIGN KEY (`ESTRELA_1`) REFERENCES `PERSONAGENS` (`NOME_DO_ATOR`);

COMMIT;


